// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppEvent struct {
	Pk            int32
	ID            uuid.UUID
	Vendor        int32
	Venue         int32
	Name          string
	Type          string
	EventDatetime pgtype.Timestamp
	Description   string
	Disclaimer    pgtype.Text
	Basecost      float64
	NumUnique     int32
	NumGa         int32
	Photo         pgtype.Text
}

type AppUser struct {
	Pk       int32
	Wallet   string
	DarkMode pgtype.Bool
}

type AppVendor struct {
	Pk     int32
	ID     uuid.UUID
	Wallet string
	Name   string
}

type AppVenue struct {
	Pk            int32
	ID            uuid.UUID
	Vendor        int32
	Name          string
	StreetAddress string
	Zip           string
	City          string
	StateCode     string
	StateName     string
	CountryCode   string
	CountryName   string
	NumUnique     int32
	NumGa         int32
	Photo         pgtype.Text
}
