name: CI-PR

on:
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    prettier:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - run: npx prettier --check .

    lint:
        runs-on: [self-hosted, test]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                    node-version: 20
                    # cache: 'npm'

            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - uses: nrwl/nx-set-shas@v4
            - run: npx nx affected -t lint
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"

    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v4
            - run: npx nx affected -t test
    build:
        runs-on: [self-hosted, test]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                #   cache: 'npm'

            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                    path: node_modules
                    key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - uses: nrwl/nx-set-shas@v4
            - run: npx nx affected -t build
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"