name: CI

on:
    push:
        branches:
            - main

permissions:
    actions: read
    contents: read

jobs:
    main:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # This enables task distribution via Nx Cloud
            # Run this command as early as possible, before dependencies are installed
            # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
            # Uncomment this line to enable task distribution
            # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

            # Cache node_modules
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v4

            # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
            # - run: npx nx-cloud record -- echo Hello World
            # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
            - run: npx nx reset
            - run: npx nx report
            - run: npx nx run-many -t lint test build --no-cloud

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::741448950585:role/GithubAction-AssumeRoleWithAction
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: 'us-east-1'

            - name: assume dev executor role credentials
              uses: aws-actions/configure-aws-credentials@v4
              if: ${{ github.event.inputs.environment == 'dev' }}
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
                  role-to-assume: arn:aws:iam::390403894969:role/GithubAction-AssumeDevAccountRole
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  role-duration-seconds: 3600
                  role-skip-session-tagging: true
                  aws-region: 'us-east-1'

            - run: npm ci --legacy-peer-deps
              working-directory: ./infra

            - name: synth dev
              if: ${{ github.event.inputs.environment == 'dev' }}
              working-directory: ./infra
              run: DEPLOYENV=dev HOSTEDZONENAME=dev.opentix.co npx cdk synth --account 390403894969 --region us-east-1 --require-approval never

            - name: deploy dev
              if: ${{ github.event.inputs.environment == 'dev' }}
              working-directory: ./infra
              run: DEPLOYENV=dev HOSTEDZONENAME=dev.opentix.co npx cdk deploy --all --account 390403894969 --region us-east-1 --require-approval never
