name: CI

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    actions: read
    contents: read

jobs:
    prettier:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - run: npx prettier --check .
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"

    lint:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - run: npx nx run-many -t lint
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"


    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
              
            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - run: npx nx run-many -t test
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"


    build-and-deploy:
        runs-on: self-hosted
        needs: [test]
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: MasterworksIO/action-local-cache@2
              id: local-cache
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}

            - run: npm i
              if: steps.local-cache.outputs.cache-hit != 'true'

            - name: Build
              run: NX_PUBLIC_APP_BUILD=$(node scripts/CreateBuildIdent.js) npx nx run-many -t build --no-cloud
              env:
                NODE_OPTIONS: "--max_old_space_size=4096"

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::741448950585:role/GithubAction-AssumeRoleWithAction
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: 'us-east-1'

            - name: assume dev executor role credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
                  role-to-assume: arn:aws:iam::390403894969:role/GithubAction-AssumeDevAccountRole
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  role-duration-seconds: 3600
                  role-skip-session-tagging: true
                  aws-region: 'us-east-1'

            - run: npm ci --legacy-peer-deps
              working-directory: ./infra

            - name: synth dev
              working-directory: ./infra
              run: DEPLOYENV=dev HOSTEDZONENAME=dev.opentix.co npx cdk synth --account 390403894969 --region us-east-1 --require-approval never

            - name: deploy dev
              working-directory: ./infra
              run: DEPLOYENV=dev HOSTEDZONENAME=dev.opentix.co npx cdk deploy --all --account 390403894969 --region us-east-1 --require-approval never

