name: Delete Feature Resources

on:
    pull_request:
        types: [closed]

env:
    AWS_DEFAULT_REGION: us-east-1

permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
    delete:
        runs-on: self-hosted
        steps:
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_PRIMARY_ACCT_ROLE }}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: 'us-east-1'

            - name: assume dev executor role credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
                  role-to-assume: ${{ secrets.AWS_DEV_ACCT_ROLE }}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  role-duration-seconds: 3600
                  role-skip-session-tagging: true
                  aws-region: 'us-east-1'

            - name: Remove Stacks for Closed PR
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}

                  echo "Looking for stacks prefixed with pr${PR_NUMBER}-"

                  PR_STACKS=$(aws cloudformation list-stacks \
                    --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE UPDATE_ROLLBACK_COMPLETE ROLLBACK_COMPLETE \
                    --query "StackSummaries[?starts_with(StackName, 'pr${PR_NUMBER}-')].StackName" \
                    --output text
                  )

                  if [ -z "$PR_STACKS" ]; then
                    echo "No matching stacks found for PR #${PR_NUMBER}."
                    exit 0
                  fi

                  for STACK in $PR_STACKS; do
                    echo "Deleting $STACK..."
                    aws cloudformation delete-stack --stack-name "$STACK"
                  done

                  echo PR_STACKS=$PR_STACKS >> $GITHUB_ENV

            - name: Comment on PR with deleted stack list
              run: |
                  if [ -z "$PR_STACKS" ]; then
                    echo "No stacks were deleted."
                    exit 0
                  fi

                  COMMENT_ID=$(gh api \
                    repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
                    -X POST \
                    -f body="Deleted feature environments: ${{ env.PR_STACKS }}" \
                    --jq '.id'
                  )

                  echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
