name: Deploy Feature Environment

on:
    workflow_dispatch:
        inputs:
            target:
                description: 'App to deploy'
                required: true
                type: choice
                options:
                    - userweb
                    - vendorweb
                default: 'userweb'

env:
    AWS_DEFAULT_REGION: us-east-1
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{env.BRANCH_NAME}}

            - name: Find associated PR
              id: find-pr
              run: |
                  PR_NUMBER=$(gh pr list \
                    --head ${{ env.BRANCH_NAME }} \
                    --json number \
                    --limit 1 \
                    --jq '.[0].number'
                  )

                  if [ -z "$PR_NUMBER" ]; then
                    echo "No PR found for branch: ${{ env.BRANCH_NAME }}"
                    exit 1
                  fi

                  echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Comment on PR
              run: |
                  COMMENT_ID=$(gh pr comment ${{ steps.find-pr.outputs.PR_NUMBER }} \
                    --body "Deployment to feature environment for app \`${{ github.event.inputs.target }}`\ has started for branch \`${{ env.BRANCH_NAME }}\`."\
                    --json id --jq .id)

                  echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_OUTPUT
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps

            - run: npx nx run ${{ github.event.inputs.target }}:build --no-cloud

            - name: Update comment with SUCCESS
              if: success()
              run: |
                  gh api \
                    repos/${{ github.repository }}/issues/comments/${{ steps.create_comment.outputs.COMMENT_ID }} \
                    -X PATCH \
                    -F body="✅ \`${{ github.event.inputs.target }}`\ Deployment succeeded for branch \`${{ env.BRANCH_NAME }}\`!"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Update comment with FAILURE
              if: failure()
              run: |
                  gh api \
                    repos/${{ github.repository }}/issues/comments/${{ steps.create_comment.outputs.COMMENT_ID }} \
                    -X PATCH \
                    -F body="❌ \`${{ github.event.inputs.target }}`\ Deployment failed for branch \`${{ env.BRANCH_NAME }}\`."
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
