name: Manual Deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                type: choice
                options:
                    - prod
                    - dev
                default: 'dev'
            branch:
                description: 'Branch to deploy from. Most likely main.'
                required: true
                type: string
                default: 'main'

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v4

            - run: npx nx reset
            - run: npx nx report
            - run: npx nx run-many -t build

            - uses: aws-actions/configure-aws-credentials@v4
              if: ${{ github.event.inputs.environment == 'prod' }}
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
                  aws-region: 'us-east-1'

            - uses: aws-actions/configure-aws-credentials@v4
              if: ${{ github.event.inputs.environment == 'dev' }}
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
                  aws-region: 'us-east-1'

            - if: ${{ github.event.inputs.environment == 'prod' }}
              working-directory: ./infra
              run: ./deploy-prod.sh

            - if: ${{ github.event.inputs.environment == 'dev' }}
              working-directory: ./infra
              run: ./deploy-dev.sh
