name: Connect to an AWS role from a GitHub repository

on:
    workflow_dispatch:

env:
    AWS_DEFAULT_REGION: us-east-1

permissions:
    id-token: write
    contents: read
jobs:
    AssumeRoleAndCallIdentity:
        runs-on: self-hosted
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{secrets.AWS_PRIMARY_ACCT_ROLE}}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: 'us-east-1'
            - name: Sts GetCallerIdentity
              run: |
                  aws sts get-caller-identity
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{secrets.AWS_PROD_ACCT_ROLE}}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: 'us-east-1'

            - name: test cloudformation list
              run: |
                  aws sts get-caller-identity
                  aws cloudformation list-stacks
